version: '3.3'

services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  vue:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  bundle:
    driver: local
  mysql_data:
    driver: local
