version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundle install
          command: cd backend && gem install bundler -v 1.17.3 && bundle install -j4 --without production
      - run:
          name: migration
          command: rails db:create db:migrate
      - run:
          name: rails t
          command: rails t
