version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    working_directory: ~/project/backend
    steps:
      - checkout
      - run:
          name: migration
          command: rails db:create db:migrate
      - run:
          name: rails t
          command: rails t
